### ISSUE TITLE
Georeference issue of geotiff files

### ISSUE THREAD

**Issue by bontekasper** [Open-EO/openeo-geotrellis-extensions#51] opened 2022-05-12 07:12 UTC
I noticed for a specific case that a georeference issue occurs when generating a tiff file, while for NetCDF file everything is correct. It seems not to happen in all situations, so it is not easy to pin-point what is exactly going wrong. A script that evokes the issue can be found here: https://git.vito.be/users/bontek/repos/e-shape/browse/Cases/Ukraine/Season_detection/test/test_tiff_bug_openeo.py 
Attached you can also find the tiff file with the georeference issue and the corresponding netcdf file of the same area.
[37TCN_active_marker_2022-05-12.zip](https://github.com/Open-EO/openeo-geotrellis-extensions/files/8675761/37TCN_active_marker_2022-05-12.zip)

**Comment by jdries** [comment] 2022-05-17 12:07
Size Geotiff/Netcdf:
11485, 11522
11264, 11264
-221,-258

Origin:
296230.,5302800.
298790.,5300240.
Diff: 2560 , 2560

The shift is the geotiff is exactly one block of 256x256 in both directions, the used chunk size.

**Comment by jdries** [comment] 2022-05-17 12:53
The script to reproduce can be made a lot simpler. 
The important thing is that two spatial filter operations are used, which is known to cause issues with geotiff georeferencing.
```
col=c.load_collection("TERRASCOPE_S2_TOC_V2",spatial_extent = {"west": 36.327926759000036, "south": 46.83564371400007, "east": 37.81145754765225, "north": 47.84737115200005},temporal_extent=["2022-05-12","2022-05-17"],bands=["B04","B08"])
col.filter_spatial(geometry.iloc[0]).execute_batch()
```

**Comment by bontekasper** [comment] 2022-05-17 13:39
So, if I understand correctly, the spatial_extent part should be removed from load_collection and only filter_spatial should be kept?

**Comment by jdries** [comment] 2022-05-17 18:17
I went a bit further, and I can reproduce it by using filter_spatial. So it's still a slightly different case from the one before.
You can just specify the extent if you need a quick workaround.
```
col=c.load_collection("TERRASCOPE_S2_TOC_V2",temporal_extent=["2022-05-15","2022-05-17"],bands=["B04"])
col.filter_spatial(geometry.iloc[0]).execute_batch()
```

**Comment by jdries** [comment] 2022-05-17 18:58
Bad result:
 Created cube for urn:eop:VITO:TERRASCOPE_S2_TOC_V2 with metadata TileLayerMetadata(int16ud32767,LayoutDefinition(Extent(296230.0, 5185040.0, 411430.0, 5302800.0),CellSize(10.0,10.0),45x46 tiles,11520x11776 pixels),Extent(299999.9999638074, 5189998.101999201, 409800.00000788155, 5300040.000020307),EPSG:32637,KeyBounds(SpaceTimeKey(1,1,1652572800000),SpaceTimeKey(44,44,1652745600000))) and partitioner Some(SpacePartitioner(KeyBounds(SpaceTimeKey(1,1,1652572800000),SpaceTimeKey(44,44,1652745600000))))
 Write Geotiff per date Extent(296230.0, 5187580.0, 411080.0, 5302800.0), GridBounds(0,0,11484,11521), TileLayout(45,46,256,256)

Good result:
 Created cube for urn:eop:VITO:TERRASCOPE_S2_TOC_V2 with metadata TileLayerMetadata(int16ud32767,LayoutDefinition(Extent(296230.0, 5185040.0, 411430.0, 5302800.0),CellSize(10.0,10.0),45x46 tiles,11520x11776 pixels),Extent(296236.62697254575, 5187585.788781411, 411079.50511527155, 5302793.379288053),EPSG:32637,KeyBounds(SpaceTimeKey(0,0,1652572800000),SpaceTimeKey(44,45,1652745600000))) and partitioner Some(SpacePartitioner(KeyBounds(SpaceTimeKey(0,0,1652572800000),SpaceTimeKey(44,45,1652745600000))))
Write Geotiff per date Extent(296230.0, 5187580.0, 411080.0, 5302800.0), GridBounds(0,0,11484,11521), TileLayout(45,46,256,256)

**Comment by jdries** [comment] 2022-05-18 06:13
So the case is triggered by:
- RDD extent smaller than layout extent (this is still normal, can occur due to globalbounds)
- CropBounds equals layout extent, so larger than RDD extent => this is weird, and in this case probably caused by differences in reprojection
- As a result, the RDD metadata had a keybounds starting at 1,1, but was not retiled before geotiff writing. The geotiff writer still took the minkey of the keybounds into account, whereas it should in fact rely on preprocessing to correct the keys.

**Comment by bontekasper** [comment] 2022-05-18 06:20
Oke great you are finding the problem, will this be something easy to fix?

**Comment by jdries** [comment] 2022-05-18 06:39
First potential fix is already committed!

**Comment by bontekasper** [comment] 2022-05-18 06:50
Oke great thanks. Just another question (I don't know if it is fully related to this problem), but when I try to mask the EVI_cube with the WorldCover layer I always got no result back (no result in case of geotiff and error in case of NETCDF). You can activate this filtering by setting 'filter_LC' to TRUE in the 'create_input_EVI_cube' 
Example of such a failing job is this: openEO batch_Ukraine_active_marker_37TCN_e91a7b29-9251-43b1-a85d-b9d5f5079f45_user bontek

**Closed** 2022-06-13 10:52 UTC
