### ISSUE TITLE
Download format extension missing at synchronous call from webviewer

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-geotrellis-extensions#15] opened 2020-10-29 14:14 UTC
When executing a synchronous call on the webviewer () by clicking "run now". The downloaded file comes without any extension. It's merely called "download". See below:

![image](https://user-images.githubusercontent.com/51962348/97585497-7b3bcd80-19f9-11eb-8148-50a44d065fc7.png)

**Comment by soxofaan** [comment] 2020-10-29 14:26
duplicate of https://github.com/Open-EO/openeo-python-driver/issues/52

**Closed by soxofaan** 2020-10-29 14:26 UTC
