### ISSUE TITLE
job-option to save results as one asset per band

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-geotrellis-extensions#309] opened 2024-06-24 13:06 UTC
For large projects, where the output is expected to be one file per s2 tile, having all the bands in one file would create too large files.
Thus the need for a job option to save the results in different files per band, as is often the case for other large products like the copernicus HRL VPP products.
Different assets should still be included in one stac item if possible. 

Implementation tasks:

- [ ] new geotiff writing approach in scala
- [ ] check STAC metadata, also the items!

## Scala implementation

I think the best place to start from is the code that now creates a tiff per date:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/83e9b63e699b6196d60c96257d7212cd89b972dd/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala#L95

In the first 'map' where we compress tiles, the bandIndex will always be 0, but we will have to add the band name to the key, which is used to group the tuples in the rdd later on.

By including the band name in the rdd key, we will get compressed bytes per date per band, and can simply write those into a geotiff in a way that is almost identical to the current approach, except for generating the right filename of course.

**Comment by JorisCod** [comment] 2024-06-25 19:50
As an additional requirement, it should be possible to define the filename through e.g. prefix and postfix, having the bandname in between. Alternatively, some kind of f-string is also an option.

**Comment by EmileSonneveld** [comment] 2024-06-26 09:03
I like Joris his suggestion. As I understand:
`file_name="openEO_{date}.tiff"`  would be the behavior we have now
`file_name="openEO_{date}_{band}.tiff"` would give a series of simple tiffs with only one band inside
`file_name="openEO_{band}.tiff"` would give a tiff for each openeo-band, with every tiff-band representing a timestamp (What Victor wants in this case)

**Comment by jdries** [comment] 2024-06-26 09:58
From what I understand, we want this:
`file_name="openEO_{date}_{band}.tiff" would give a series of simple tiffs with only one band inside`
multiple timestamps in single tiff is not supported by standard geotiff tooling (gdal) and can not be described easily in stac so we prefer to stay away from that, especially for lcfm

**Comment by VictorVerhaert** [comment] 2024-06-26 10:05
The yearly and seasonal features don't require timestamps.

For the Monthly composites we might have to consider if creating a tiff per bands per month per tile might result in to many files. (Hence the idea of having a band per "timestamp", the timestamp being a monthly composite)

**Comment by jdries** [comment] 2024-08-09 13:45
@EmileSonneveld  important here is that the writing happens on the executors. Now it happens on the driver, but takes a long time, so executors are idle while waiting for driver to finish, which is costly.

**Comment by EmileSonneveld** [comment] 2024-08-13 12:52
@jdries , what would be the best interface?
```python
datacube = datacube.save_result(
    format="GTiff",
    options={"separate_files_per_band": True}
)
# or:
datacube.execute_batch(
    format="GTiff",
    title="test job",
    separate_files_per_band=True,
)
```
The `save_results` version is handy when there are miltiple `save_result` nodes. However, it won't make much sense when specified in a sync job.

Is `separate_files_per_band` a good name?

**Comment by VictorVerhaert** [comment] 2024-08-14 07:43
I prefer the first option, as it is more versatile. I don't think we need files per band for sync jobs as these often only have one file.

As a name I would stick with `separate_asset_per_band` as it is more in line with our terminology throughout openEO.

**Comment by soxofaan** [comment] 2024-08-20 10:49
FYI: make sure to document this new format parameter e,g, at https://github.com/Open-EO/openeo-geopyspark-driver/blob/71f925859e90d95b48bbe2fe987f9c3f26649b1f/openeogeotrellis/backend.py#L412-L456, then user can automatically discover this, e.g. from the web editor 
![image](https://github.com/user-attachments/assets/e903117e-bda3-490b-b44c-5b279c43fa99)

**Comment by EmileSonneveld** [comment] 2024-08-21 10:12
Some notes
- in many cases, one can specify separate_asset_per_band, but nothing will happen. (for example when using netcdf)
- band names are used. They could cause problems with special characters, but should be rare case
- if no band names are usable, band0, band1, ... is used (only encountered in Scala testing for the moment)
- now all bands are bound as a MultibandTile per SpatialTemporal key in scala, there might some parallel gains by keeping bands separate. Also, low resolution bands will still folow the high resolution bands.
- Tiffs with band names end up in STAC metadata

**Comment by VictorVerhaert** [comment] 2024-08-21 11:10
One edge case that might be considered: does this job option work when an export_workspace is used after the save_result?
Should we create another issue for this?

**Comment by soxofaan** [comment] 2024-08-21 14:49
If I understand #843 correctly, this new format option was not added yet to https://github.com/Open-EO/openeo-geopyspark-driver/blob/390c2651bc4ce3b7c20f5efde2df030ddaf9310a/openeogeotrellis/backend.py#L413-L456

so I think that is a follow up thing to do:

- [ ] list new format option for GeoTIFF output format at  `/file_formats` endpoint

> one edge case that might be considered: does this job option work when an export_workspace is used after the save_result

important subtlety to consider: this is about adding a _format_ option (parameter in `save_result`), not a _job_ option (which works at another level).

> in many cases, one can specify separate_asset_per_band, but nothing will happen. (for example when using netcdf)

This is actually another interesting aspect of making this a format option (instead of job option): we could detect  unsupported format options and trigger a warning (or even throwing an error).

**Comment by EmileSonneveld** [comment] 2024-08-21 17:10
This is available on CDSE staging.
Some early performance measurments:
|                   |  wall time | max mem | credits | job-id                             |
|-------------------|------------|---------|---------|------------------------------------|
|classical          |   506s     |  2.1Gb  |       8 | j-240821262ae144e3aa5ecd9e9de357d6 |
|per band           |   740s     |  2.3Gb  |      13 | j-2408217c720f4b60a04579d2d441c8e1 |
|per band + time dim|   758s     |  2.2Gb  |      13 | j-240821aa930c4093b6f547e60e6966e7 |


Performance seems not better. probably because the bands are frist toegether in multiband tiles and get splitted in an extra step, shuffeling some data around

Edit: added credits and job-id column

**Comment by EmileSonneveld** [comment] 2024-08-21 17:11
All band metadata is still shown for every tiff file in the editor. Need to check that

Also, current syntax:
```python
datacube = datacube.save_result(format="GTiff", options={"separate_asset_per_band": True})
```

**Comment by JeroenVerstraelen** [comment] 2024-08-22 08:47
- Compare credits plus info in spark UI instead of wall clock time.

**Comment by jdries** [comment] 2024-08-22 11:41
the job per band simply submits a large amount of very small spark jobs, which is likely caused by the pyramid generation.
So turning of pyramids in the meantime is one option, but in the end we will have to update the implementation to simply create and store the geotiff on the executors.

**Comment by EmileSonneveld** [comment] 2024-08-22 11:53
Is this also the case when there is an (empty) temporal dimension? In this case the tiffs should be written from the executors and there is no overview code there too

**Comment by EmileSonneveld** [comment] 2024-08-28 12:34
- It will now raise error when `separate_asset_per_band` is used with unsupported format (only gtiff supported)
- In a test-case, credit usage varied between 8 and 12. This is a known issue before.
- `separate_asset_per_band` is visible in GeoTiff options: ([also link](https://openeo-staging.dataspace.copernicus.eu/openeo/file_formats))
![image](https://github.com/user-attachments/assets/aeb329fc-3e79-456f-9ae7-7d0e4570b29a)

@VictorVerhaert nothing more to do in this ticket?

**Comment by VictorVerhaert** [comment] 2024-08-28 12:38
I can confirm that this option works well with the `export_workspace` process.
Checking the file name requirements right now.

**Comment by EmileSonneveld** [comment] 2024-09-02 11:16
I'll close this ticket. If something comes up, we can create a new one

**Closed as completed by EmileSonneveld** 2024-09-02 11:16 UTC
Labels: enhancement
